{
 "title": "SRE Portfolio",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Job Creation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(api_jobs_total[5m])\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(api_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Jobs Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_jobs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API P95 Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}