# -----------------------------------------------------------------------------
# values-dev.yaml -- Worker dev overrides
# -----------------------------------------------------------------------------
image:
  repository: sre-portfolio-worker
  tag: 7e006247
  pullPolicy: Never

replicaCount: 1
env: dev
sqsQueueUrl: ""
irsaRoleArn: ""
