# -----------------------------------------------------------------------------
# values-dev.yaml -- Worker dev overrides
# -----------------------------------------------------------------------------
image:
  repository: sre-portfolio-worker
  tag: f1f56cb2
  pullPolicy: Never

replicaCount: 1
env: dev
sqsQueueUrl: ""
irsaRoleArn: ""
